### PR TITLE
Added Teams page

### PR DESCRIPTION
**Pull request by octoper**
## Added
- Teams page (@nunomaduro proposed it here: [Missing the team on the website](https://github.com/pestphp/pest/issues/35#issue-625305164))

## Fixes
- Changed 404 page

### CODE REVIEW

**Comment by alexmartinfr** [comment]
Nice work!
Here is a screenshot demoing the PR:
Capture d’écran 2020-05-30 à 16 07 36

We should move the Active Core Team Members at the end of the page, though.

The reading flow would go:

```
- Hey! You like Pest and want to be part of the team?
- Reach out to us (discord link?) if you can help with any of the following:

- (list of open positions)

- Core Team Members

- (list of members)
```

**Comment by octoper** [comment]
Nice @AlexMartinFR  I will make the changes!

**Comment by nunomaduro** [comment]
Huge huge huge job. Thank you @octoper

**Comment by alexmartinfr** [comment]
Great work!

(Sorry about my last commit, I pasted the wrong code on `team.php`.
Fixed it as soon as I saw that so it never was live.)

**Comment by octoper** [comment]
@AlexMartinFR in team.php you need to change the links property on you
```
"links":[
    "name": "Instagram",
    "url":"https://Instagram.com"
]
```
I've done this for betteraccessibility

**Comment by alexmartinfr** [comment]
Yup I saw that, it's fixed :)

**Pull request merged**
