### PR TITLE
Made some changes

### PR DESCRIPTION
**Pull request by octoper**
I have made some changes to the Pest website

## Changes

- Upgraded TailwindCSS from v1.0.3 to v1.4.6
- Added Tailwind UI to tailwind.config.js file and removed the CDN stylesheets (for some speed improvement)
- Made some visual changes to the Documentation
- Made some accessibility and speed improvements

### CODE REVIEW

**Comment by nunomaduro** [comment]
@octoper This pull request sounds doooope! Give me a couple of hours and I will take a look.

**Comment by alexmartinfr** [comment]
I just had a look through everything, and it looks great to me!

**Comment by octoper** [comment]
Take your time! 
I will make some more improvements tomorrow.

**Comment by alexmartinfr** [comment]
Oh I didn't see the last ones!

If I may, I liked your original idea of putting the active menu item in bold, I think it needs a bit more emphasis than it has now. Did you revert it for a particular reason?

Also, just an idea, but I find the menu items a tiny bit too wide appart in the actual documentation. I like Tailwind's more condensed approach: https://tailwindcss.com/docs/installation/

I was planning on doing something for that, but it needed a custom Tailwind padding value, or the new `py-1.5` TailwindUI features. I have a feeling you would fix that easily :)

**Comment by octoper** [comment]
Oh thanks for noticing that i just deleted `.font-semibold` by mistake

I did it but I don't see any big difference, I used `.py-1.5` from TailwindUI

@nunomaduro What do you think?

screenshot

**Comment by alexmartinfr** [comment]
What I would personally aim for, to separate the sections a bit more:
(I cheated a little, I set some of the values directly on the browser, but we could find close Tailwind default or configure custom values for them)

Capture d’écran 2020-05-25 à 22 38 41


Modifications:

- menu headers (like "Getting Started" & so): `margin-top: .75rem; margin-bottom: .5rem;`

- vertical padding on menu item: `.45rem`
- width on menu item (for large screen):  `lg:w-56` (= 14rem on TW)
- background color on active menu item: `bg-gray-200`
- text-color on active menu item: `text-gray-700`

Also, on my screenshot, I'm using the **System-UI** fontstack you proposed, but only for the menu.
I kept Nunito for the content, it's a pretty font :)

**Comment by octoper** [comment]
Yeah that's is looking nice.
I have a question thought what is the `font-weight` you have set there?

**Comment by alexmartinfr** [comment]
Oh right, I forgot about that!

600 on the active menu item, 500 on the others.

Adam Wathan uses only 500 on TailwindUI's doc, but for some reason it doesn't work as well here. Probably because we are using monochromatic text.

(Which I like in a way. We don't need the menu to distract us while we read)


Edit : Also, I limited the menu item length in this design proposal, because I keep clicking different menu items by mistake in the actual one 😉
Plus it will look better if we go with the background color.

**Comment by octoper** [comment]
Oh I think its like that beacause he uses Inter Font Family

**Comment by octoper** [comment]
I think that is nice for now.
I will take a look tomorrow how it look likes with Inter Font.
image

**Comment by alexmartinfr** [comment]
Oh I know why our screenshot looks different.

When switching from Tailwind to TailwindUI, `bg-gray-200`becomes `bg-cool-gray-200`.
I think the cool variant we have right now works very well with Pest "vibrant" branding colors 🙂

They added a new default gray, with a less pronounced tint:
Capture d’écran 2020-05-25 à 23 20 44


Thanks for your great work @octoper , this is a very nice contribution 👌

(About the Inter font, I think the system stack works well here and prevent from loading yet another font though)

**Comment by nunomaduro** [comment]
@AlexMartinFR Can you follow this development? If is good for you, you can merge;

**Comment by alexmartinfr** [comment]
Sure! I'll do a thorough review/testing tonight 👍

Edit: I'm on it now.

**Comment by octoper** [comment]
That looks nice!
I think it's time you merge, If you are good with that.

**Review by alexmartinfr — APPROVED** [review]

**Comment by alexmartinfr** [comment]
Yup, I was just done testing/reviewing everything!
Great work, octoper :)

**Comment by octoper** [comment]
Thank you!
You helped me a lot @AlexMartinFR thank you!

**Pull request merged**
