### PR TITLE
Made side navbar scrollable

### PR DESCRIPTION
**Pull request by octoper**
## Changes
- Made side navbar on docs scrollable (idea from [TailwindCSS Docs](https://tailwindcss.com/))

### CODE REVIEW

**Comment by nunomaduro** [comment]
@octoper Can you fix conflicts?

**Comment by octoper** [comment]
@nunomaduro What conflicts? 😅

**Comment by nunomaduro** [comment]
Screenshot 2020-06-18 at 11 44 28

**Comment by octoper** [comment]
@nunomaduro It's ready

**Comment by nunomaduro** [comment]
Thanks!

**Pull request merged**
