### PR TITLE
Image optimizations

### PR DESCRIPTION
**Pull request by alexmartinfr**
- New terminal screenshots for **Installation** & **Pest From Scratch**.
- Image size optimizations for some assets which were taking a long time to load on slow Internet.

### CODE REVIEW

**Comment by owenvoke** [comment]
@AlexMartinFR, just wondering, what did you use to create the screenshot? And also, what did you use for the image optimisation? 🙂

I've recently been using this GitHub Action, and wonder if it'd be a good fit for here maybe?
https://github.com/calibreapp/image-actions

**Comment by alexmartinfr** [comment]
@owenvoke  For the terminal "frame", I'm using one made with the help of [carbon.now.sh](https://carbon.now.sh/).
Then, I'm using Affinity Photo to paste a capture of my own terminal in it, customize the padding, font scale, etc 😉

For the image optimization, I've taken the easy route: [tinypng.com](https://tinypng.com/) or [compressor.io](https://compressor.io/). Both have quite good presets regarding size/quality balance.
I've worked with _pngquant_ and such CLI tools in the past, but it's tricky to achieve good results on every images without sacrificing either size or quality, I've found.

I'm curious about this GtitHub Action though, nice find!
I would particularly check what happens to a PNG with shadows, and a JPG with flat surfaces.
Both can easily get crushed/filled with artefacts with a bit too much compression.

**Comment by octoper** [comment]
@AlexMartinFR @owenvoke I think I can add the image optimize action tommorow

**Comment by owenvoke** [comment]
Just for reference, this is my workflow file for running it, should be able to add it to `.github/workflows/compress-images.yml`.
```yml
name: Compress

on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.png'
      - '**.webp'
      - '**.avif'

jobs:
  compress-images:
    runs-on: ubuntu-latest

    name: Images

    steps:

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Compress images
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

**Pull request merged**
