### PR TITLE
Updated pest requirements documentation

### PR DESCRIPTION
**Pull request by raingrave**
Your requirements could not be resolved to an installable set of packages

### CODE REVIEW

**Comment by raingrave** [comment]
not resolved

**Comment by owenvoke** [comment]
Looks like it needs to be `9.3.7` or `9.3.8` due to the use of internal classes. 🤔😕 https://github.com/pestphp/pest/blob/master/composer.json#L25

I feel like this requirement is kind of annoying though, but not sure we can use `~9.3.8`

**Comment by nunomaduro** [comment]
This needs to be addressed.

**Comment by owenvoke** [comment]
@nunomaduro, do you know what internal classes we are using? And whether we'd be able to use a `~` for the version?

**Pull request merged**
